# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Test

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn build

      # - name: Create zip file
      #   run: node archive.js

      # - name: Submit
      #   run: |
      #     npx chrome-webstore-upload-cli@2 upload --source dist.zip --auto-publish
      #   env:
      #     # https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md
      #     EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
      #     CLIENT_ID: ${{ secrets.CLIENT_ID }}
      #     CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      #     REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

      # - name: Create release draft
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ steps.daily-version.outputs.version }}
      #     generate_release_notes: true
      #     files: dist.zip
